#include <SFML\Graphics.hpp>
#include <iostream>
#include <string>

using namespace sf;
//Текстова змінна, яка містить в собі всі ігрові рівні
String TileMap[12][20] = {
{//T-Tree;H-Health;O-Coin;C-Cbble;G-Grass;D-Stone;0-9,W,Q-Enemys,B-Box;
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T                                T     TTTTTTTTTTT",
	"T                                T     TTTTTTTTTTT",
	"T  H                    OOO    TTT     TTTTTTTTTTT",
	"T                               PT     TTTTTTTTTTT",
	"T                       T  T     T     TTTTTTTTTTT",
	"T    TT   TT       TT         TTTT    HTTTTTTTTTTT",
	"T                                T     TTTTTTTTTTT",
	"T       OOOO    C        OOO     T     TTTTTTTTTTT",
	"T               CC               TT O  TTTTTTTTTTT",
	"TL              CC                     TTTTTTTTTTT",
	"T    CB  4      CC   4    CC     4     TTTTTTTTTTT",
	"GGGGGCGGGGGGGGGGCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T      PT               T     OT       TTTTTTTTTTT",
	"T       T                      T   OO  TTTTTTTTTTT",
	"T   TTTTT           O        TTT       TTTTTTTTTTT",
	"T  T              O     T    TL        TTTTTTTTTTT",
	"T      O  OO    O      TT    T         TTTTTTTTTTT",
	"T                     C     TTTTTT     TTTTTTTTTTT",
	"TT         TTT       CC    T          TTTTTTTTTTTT",
	"T  OO TT      T    CCCC   TT          TTTTTTTTTTTT",
	"T                 CCCCC       TTTT   OTTTTTTTTTTTT",
	"TC  CCH    C      CCCCC      OTH      TTTTTTTTTTTT",
	"TC  CC  1  C  1  CCCCCC   1   TB  1   TTTTTTTTTTTT",
	"GCGGCCGGGGGCGGGGGCCCCCCCGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T   TL    T                            TTTTTTTTTTT",
	"T   T     T                            TTTTTTTTTTT",
	"T   TTT   T                            TTTTTTTTTTT",
	"T  OO     T                            TTTTTTTTTTT",
	"T  B 1    T                            TTTTTTTTTTT",
	"T  TTTTTTTT                   H        TTTTTTTTTTT",
	"T     OO     OOOO    CC                TTTTTTTTTTT",
	"T                   CC                 TTTTTTTTTTT",
	"TC                 CCO                 TTTTTTTTTTT",
	"TCCC               CC                 PTTTTTTTTTTT",
	"TCCCCC       5     CC    5  CC 5       TTTTTTTTTTT",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T    OO         TTTTTTTTT  TT  TTTTTTTTTTTTTTTTTTT",
	"TL                        OTT   TTTTTTTTTTTTTTTTTT",
	"T    0  TTT                TT       TTTTTTTTTTTTTT",
	"TTTTTTTTTTTTTT    TTTT     TTH         TTTTTTTTTTT",
	"T           HTTTTTT   T    TT      OOOOTTTTTTTTTTT",
	"T  OO   OO   T             TT         HTTTTTTTTTTT",
	"T                          TT     TTTTTTTTTTTTTTTT",
	"T   TTTT    TTT    TTTTT   TT     TTTTTTTTTTTTTTTT",
	"T   TTTTTTTTTTT   TT   T   TT          TTTTTTTTTTT",
	"T                 T                   PTTTTTTTTTTT",
	"TB  0         4   TB0           4T     TTTTTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
	"C      CCCCCCC         H CCOO          CCCCCCCCCCC",
	"CL        CCCC           CC          OOCCCCCCCCCCC",
	"C         CCCC    C   6  CCCCCC        CCCCCCCCCCC",
	"CCCCCCC   CCCC    CCCCCCCCC      C  6  CCCCCCCCCCC",
	"CCCCCCC   CCCC      CCCCC        CCCCCCCCCCCCCCCCC",
	"CCCCCCC   CCCCCC     CC            OO  CCCCCCCCCCC",
	"C H       CCCCCCC    CC    CCCC        CCCCCCCCCCC",
	"C           OOO              OCC      PCCCCCCCCCCC",
	"C                O             C 6     CCCCCCCCCCC",
	"C    C   CCCCC              B   CCCCCCCCCCCCCCCCCC",
	"C                  CCC    CCC          CCCCCCCCCCC",
	"CDDDDDDDCCCDDDDDDDCCDDDDDCCCCDDDCCDDDDCCCCCCCCCCCC",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T                      OO              TTTTTTTTTTT",
	"T             OO                       TTTTTTTTTTT",
	"T                             OO       TTTTTTTTTTT",
	"T       T    OO    T                 OOTTTTTTTTTTT",
	"T                      T               TTTTTTTTTTT",
	"TTTTTTTT     T     OO                  TTTTTTTTTTT",
	"T      O  O               T      T     TTTTTTTTTTT",
	"TP              OO                    LTTTTTTTTTTT",
	"T                   B  T           T   TTTTTTTTTTT",
	"TTT                TT              TTTTTTTTTTTTTTT",
	"T   7      7            7        7     TTTTTTTTTTT",
	"GGGGGGGGGGTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{//T-Tree;H-Health;O-Coin;C-Cbble;G-Grass;D-Stone;B-Box;0-9,W,Q-Enemys;A-BOSS;
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T     TT           T            TT     TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"TP          TT           TT           LTTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"TTT                                 TTTTTTTTTTTTTT",
	"T                 A                    TTTTTTTTTTT",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
},
{
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"T                                      TTTTTTTTTTT",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
}};
//Встановлює карту рівня, переданого в функцію
void setTileMap(int i, String text[]) {
	for (int j = 1; j < 20; j++)
	{
		TileMap[i][j] = text[j];
	}
}
//Перегрузка того ж метода з стандартним string
void setTileMap(int i, std::string text[]) {
	for (int j = 1; j < 20; j++)
	{
		TileMap[i][j] = text[j];
	}
}
//Передає потрібний рядок рівня
String getTileMap(int i, int j) {
	return TileMap[i][j];
}
//Встановлює стандартну карту
void setTileMapDefault() {
	TileMap[0][0] =	 "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
	TileMap[0][1] =  "T                                T     TTTTTTTTTTT";
	TileMap[0][2] =  "T                                T     TTTTTTTTTTT";
	TileMap[0][3] =  "T  H                    OOO    TTT     TTTTTTTTTTT";
	TileMap[0][4] =  "T                               PT     TTTTTTTTTTT";
	TileMap[0][5] =  "T                       T  T     T     TTTTTTTTTTT";
	TileMap[0][6] =  "T    TT   TT       TT         TTTT    HTTTTTTTTTTT";
	TileMap[0][7] =  "T                                T     TTTTTTTTTTT";
	TileMap[0][8] =  "T       OOOO    C        OOO     T     TTTTTTTTTTT";
	TileMap[0][9] =  "T               CC               TT O  TTTTTTTTTTT";
	TileMap[0][10] = "TL              CC                     TTTTTTTTTTT";
	TileMap[0][11] = "T    CB  4      CC   4    CC     4     TTTTTTTTTTT";
	TileMap[0][12] = "GGGGGCGGGGGGGGGGCCGGGGGGGGCCGGGGGGGGGGGGGGGGGGGGGG";
	TileMap[0][13] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[0][14] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[0][15] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[0][16] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[0][17] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[0][18] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[0][19] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[0][20] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[1][0] =  "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
	TileMap[1][1] =  "T      PT               T     OT       TTTTTTTTTTT";
	TileMap[1][2] =  "T       T                      T   OO  TTTTTTTTTTT";
	TileMap[1][3] =  "T   TTTT            O        TTT       TTTTTTTTTTT";
	TileMap[1][4] =  "T  T              O     T    TL        TTTTTTTTTTT";
	TileMap[1][5] =  "T      O  OO    O      TT    T         TTTTTTTTTTT";
	TileMap[1][6] =  "T                     C     TTTTTT     TTTTTTTTTTT";
	TileMap[1][7] =  "TT         TTT       CC    T          TTTTTTTTTTTT";
	TileMap[1][8] =  "T  OO TT      T    CCCC   TT          TTTTTTTTTTTT";
	TileMap[1][9] =  "T                 CCCCC       TTTT   OTTTTTTTTTTTT";
	TileMap[1][10] = "TC  CCH    D      CCCCC      OTH      TTTTTTTTTTTT";
	TileMap[1][11] = "TC  CC  1  D  1  CCCCCC   1   TB  1   TTTTTTTTTTTT";
	TileMap[1][12] = "GCGGCCGGGGGGGGGGGCCCCCCCGGGGGGGGGGGGGGGGGGGGGGGGGG";
	TileMap[1][13] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[1][14] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[1][15] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[1][16] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[1][17] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[1][18] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[1][19] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[1][20] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[2][0] =  "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
	TileMap[2][1] =  "T   TL    T                            TTTTTTTTTTT";
	TileMap[2][2] =  "T   T     T                            TTTTTTTTTTT";
	TileMap[2][3] =  "T   TTT   T                            TTTTTTTTTTT";
	TileMap[2][4] =  "T  OO     T                            TTTTTTTTTTT";
	TileMap[2][5] =  "T  B 1    T                            TTTTTTTTTTT";
	TileMap[2][6] = "T  TTTTTTTT                    H       TTTTTTTTTTT";
	TileMap[2][7] =  "T     OO     OOOO    CC                TTTTTTTTTTT";
	TileMap[2][8] =  "T                   CC                 TTTTTTTTTTT";
	TileMap[2][9] =  "TC                 CCO                 TTTTTTTTTTT";
	TileMap[2][10] = "TCCC               CC       C         PTTTTTTTTTTT";
	TileMap[2][11] = "TCCCCC       5     CC    5  C  5       TTTTTTTTTTT";
	TileMap[2][12] = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG";
	TileMap[2][13] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[2][14] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[2][15] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[2][16] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[2][17] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[2][18] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[2][19] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[2][20] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[3][0] =  "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
	TileMap[3][1] =  "T    OO         TTTTTTTTT  TT  TTTTTTTTTTTTTTTTTTT";
	TileMap[3][2] =  "TL                        OTT   TTTTTTTTTTTTTTTTTT";
	TileMap[3][3] =  "T    0  TTT                TT       TTTTTTTTTTTTTT";
	TileMap[3][4] =  "TTTTTTTTTTTTTT    TTTT     TT          TTTTTTTTTTT";
	TileMap[3][5] =  "T           HTTTTTT   T    TTH     OOOOTTTTTTTTTTT";
	TileMap[3][6] =  "T  OO   OO   T             TT         HTTTTTTTTTTT";
	TileMap[3][7] =  "T                          TT     TTTTTTTTTTTTTTTT";
	TileMap[3][8] =  "T   TTTT    TTT    TTTTT   TT     TTTTTTTTTTTTTTTT";
	TileMap[3][9] =  "T   TTTTTTTTTTT   TT   T    T          TTTTTTTTTTT";
	TileMap[3][10] = "T                 T                   PTTTTTTTTTTT";
	TileMap[3][11] = "TB  0         4   TB0           4T     TTTTTTTTTTT";
	TileMap[3][12] = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
	TileMap[3][13] = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
	TileMap[3][15] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[3][16] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[3][17] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[3][18] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[3][19] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[3][20] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[4][0] =  "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC";
	TileMap[4][1] =  "C      CCCCCCC         H CCOO          CCCCCCCCCCC";
	TileMap[4][2] =  "CL        CCCC           CC          OOCCCCCCCCCCC";
	TileMap[4][3] =  "C         CCCC    C   6  CCCCCC        CCCCCCCCCCC";
	TileMap[4][4] =  "CCCCCCC   CCCC    CCCCCCCCC      C  6  CCCCCCCCCCC";
	TileMap[4][5] =  "CCCCCCC   CCCC      CCCCC        CCCCCCCCCCCCCCCCC";
	TileMap[4][6] =  "CCCCCCC   CCCCCC     CC            OO  CCCCCCCCCCC";
	TileMap[4][7] =  "C H       CCCCCCC    CC    CCCC        CCCCCCCCCCC";
	TileMap[4][8] =  "C           OOO              OCC      PCCCCCCCCCCC";
	TileMap[4][9] =  "C                O             C 6     CCCCCCCCCCC";
	TileMap[4][10] = "C    C   CCCCC              B   CCCCCCCCCCCCCCCCCC";
	TileMap[4][11] = "C                  CCC    CCC          CCCCCCCCCCC";
	TileMap[4][12] = "CDDDDDDDCCCDDDDDDDCCDDDDDCCCCDDDCCDDDDCCCCCCCCCCCC";
	TileMap[4][13] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[4][14] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[4][15] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[4][16] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[4][17] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[4][18] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[4][19] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[4][20] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[5][0] = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
	TileMap[5][1] = "T                      OO              TTTTTTTTTTT";
	TileMap[5][2] = "T             OO                       TTTTTTTTTTT";
	TileMap[5][3] = "T                             OO       TTTTTTTTTTT";
	TileMap[5][4] = "T       T    OO    T                 OOTTTTTTTTTTT";
	TileMap[5][5] = "T                      T               TTTTTTTTTTT";
	TileMap[5][6] = "TTTTTTTT     T     OO                  TTTTTTTTTTT";
	TileMap[5][7] = "T      O  O               T      T     TTTTTTTTTTT";
	TileMap[5][8] = "TL              OO                    PTTTTTTTTTTT";
	TileMap[5][9] = "T                   B  T           T   TTTTTTTTTTT";
	TileMap[5][10] = "TTT                TT              TTTTTTTTTTTTTTT";
	TileMap[5][11] = "T       7             7         7      TTTTTTTTTTT";
	TileMap[5][12] = "GGGGGGGGGGTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG";
	TileMap[5][13] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[5][14] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[5][15] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[5][16] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[5][17] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[5][18] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[5][19] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[5][20] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[6][0] = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT";
	TileMap[6][1] = "T                                      TTTTTTTTTTT";
	TileMap[6][2] = "T                                      TTTTTTTTTTT";
	TileMap[6][3] = "T                                      TTTTTTTTTTT";
	TileMap[6][4] = "T     TT           T            TT     TTTTTTTTTTT";
	TileMap[6][5] = "T                                      TTTTTTTTTTT";
	TileMap[6][6] = "T                                      TTTTTTTTTTT";
	TileMap[6][7] = "T                                      TTTTTTTTTTT";
	TileMap[6][8] = "TL          TT           TT           PTTTTTTTTTTT";
	TileMap[6][9] = "T                                      TTTTTTTTTTT";
	TileMap[6][10] = "TTT                                TTTTTTTTTTTTTT";
	TileMap[6][11] = "T                 A                    TTTTTTTTTTT";
	TileMap[6][12] = "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG";
	TileMap[6][13] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[6][14] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[6][15] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[6][16] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[6][17] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[6][18] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[6][19] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
	TileMap[6][20] = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD";
}